# GNU as for AArch64.

comment = [
    '//',
    '^#',
    { begin = '^#.*\\$', end = '(?:^|[^\\])$', multiline = true },
    { begin = '/\*', end = '\*/', multiline = true },
]
literal = [
    { begin = '"', end = '"', escape = '\' },
    { begin = '''\B'(?:\\(?:[0-7]{1,3}|[xX][0-9A-Fa-f]+|.)|.)'?''' },
]
label = ['(?:[\w.$]+|"(?:[^"\\]|\\.)*"):']
separator = [';']
continuation = ['\\']

directive = ['.*']

[[block]]
begin = ['.if*']
middle = ['.elseif', '.else']
end = ['.endif']

[[block]]
begin = ['.macro']
end = ['.endm']

[[block]]
begin = ['.rept', '.irp', '.irpc']
end = ['.endr']
